# Generated by Django 5.2.3 on 2025-07-15 12:18

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.getfilename)),
                ('desc', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-Show,1-hidden')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vendor', models.CharField(max_length=150)),
                ('prod_image', models.ImageField(blank=True, null=True, upload_to=shop.models.getfilename)),
                ('quantity', models.IntegerField()),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('desc', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-Show,1-hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('catof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catog')),
            ],
        ),
    ]
