# Generated by Django 5.2.3 on 2025-07-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav',
            name='product_qty',
        ),
    ]
